server:
  servlet:
    context-path: /jpa

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/jpadb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true